import type {SystemRow} from './types';

/** 主机厂可配默认系统模板（一期种子数据，后台可 CRUD） */
export const OEM_SYSTEM_TEMPLATE: Omit<SystemRow, never>[] = [
  {
    id: 'body',
    nameZh: '车身',
    nameEn: 'Body structure',
    sortOrder: 10,
    color: '#8fb3c9',
    descriptionZh: '白车身、梁柱、地板、覆盖件等主体结构。',
    descriptionEn: 'Body-in-white, pillars, floor and major panels.',
  },
  {
    id: 'closures',
    nameZh: '开闭件',
    nameEn: 'Closures',
    sortOrder: 20,
    color: '#9ec4a8',
    descriptionZh: '四门两盖、滑移门、尾门等开闭系统。',
    descriptionEn: 'Doors, hood, liftgate and related closures.',
  },
  {
    id: 'edrive',
    nameZh: '三电',
    nameEn: 'Electric drive',
    sortOrder: 30,
    color: '#e0a56d',
    descriptionZh: '电池、电机、电控及相关高压附件。',
    descriptionEn: 'Battery, drive units, power electronics and HV parts.',
  },
  {
    id: 'chassis',
    nameZh: '底盘',
    nameEn: 'Chassis',
    sortOrder: 40,
    color: '#b7a4d4',
    descriptionZh: '悬架、转向、制动卡钳以外的底盘总成。',
    descriptionEn: 'Suspension, steering and related chassis assemblies.',
  },
  {
    id: 'wheels',
    nameZh: '车轮与制动',
    nameEn: 'Wheels and brakes',
    sortOrder: 50,
    color: '#d0d5db',
    descriptionZh: '轮胎、轮毂、制动盘与相关紧固件。',
    descriptionEn: 'Tires, wheels, brake discs and fasteners.',
  },
  {
    id: 'interior',
    nameZh: '内饰',
    nameEn: 'Interior',
    sortOrder: 60,
    color: '#c9b8a0',
    descriptionZh: '座椅、仪表板、内饰饰板与乘员舱件。',
    descriptionEn: 'Seats, instrument panel, trim and cabin parts.',
  },
  {
    id: 'exterior',
    nameZh: '外饰',
    nameEn: 'Exterior trim',
    sortOrder: 70,
    color: '#7eb6d4',
    descriptionZh: '灯具、饰条、格栅、玻璃与外饰件。',
    descriptionEn: 'Lighting, moldings, grille, glass and exterior trim.',
  },
  {
    id: 'other',
    nameZh: '其他',
    nameEn: 'Other',
    sortOrder: 90,
    color: '#8a96a2',
    descriptionZh: '暂未归类或跨系统件。',
    descriptionEn: 'Unclassified or cross-system pieces.',
  },
];
